### PR TITLE
starpu: do not browse rdeps for task pruning

### PR DESCRIPTION
**Pull request by sthibaul**
StarPU will anyway only submit tasks for which data actually passed is
local.

### CODE REVIEW

**Comment by sthibaul** [comment]
I have not actually tested it, but I do not see why reverse dependencies would be needed: only the direct dependencies are passed to the tasks, and that's only what counts for starpu to discard them or not

**Comment by eddy16112** [comment]
I can explain why I have the reverse_dep, here is a example:
1-> 2, 2->3. 
the graph is like this:
1
    2
3
Task 1 3 are in node 0, and 2 in node 1. 1 2 3 are in 1st 2nd and 3rd time step receptively.
The correct task insertion sequence is 1,2,3 in both node 0 and 1. 

My code is like this:
for t in 1 2 3 {
  check if t is local
  check if t's parents are local (dep)
  check if t's children are local (reverse_dep)
}
If there is no reverse_dep check, then in node 1, the t1 is not inserted before t2. 

Anyway, that is how parsec prune tasks, I just copied it here. Maybe it is not needed for starpu. If all tests passed, we can remove it. Thanks for letting me know.

**Comment by eddy16112** [comment]
I see, thank you

**Comment by sthibaul** [comment]
ping on this?

**Pull request merged**
